name: testgo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    defaults:
      run:
        working-directory: my-turborepo
    name: docker build if docker file changed
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
            apps/web/node_modules
            packages/shared/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build shared package
        run: npm run build 

      - name: Push to ghcr.io
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          GH_USERNAME: ${{secrets.GH_USERNAME}}
        run: |
          RELEASEVERSION=1.12
          #
          echo "Docker testgo changed so building then pushing..."
          echo $GH_TOKEN | docker login ghcr.io -u $GH_USERNAME --password-stdin &
          docker build . --tag ghcr.io/pkellner/testgo:latest --tag ghcr.io/pkellner/testgo:$RELEASEVERSION 
          docker push ghcr.io/pkellner/testgo --all-tags
          
